name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.3.5'

    - run: mdbook build docs

    # Build WASM Examples
    - name: Install libgtk-dev
      run: |
          sudo apt update
          sudo apt install libgtk-3-dev

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        profile: minimal
        override: true

    - name: Build WASM examples
      run: wasm-pack build --target web druid/examples/wasm

    - name: Copy wasm artifacts to docs
      run: cp -r ./druid/examples/wasm/pkg ./docs/book/pkg

    # Deploy all artifacts
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs/book
